services:
  postgres-db:
    container_name: postgres-db
    image: postgres:15.5-alpine
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - 5432:5432
    user: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 3s
      timeout: 15s
      retries: 5

  apps:
    depends_on:
      - postgres-db
    container_name: apps
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/frontend/node_modules
      - /app/backend/node_modules
